newrelic/newrelic-k8s-metrics-adapter

charts/newrelic-k8s-metrics-adapter/.helmignore, charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/README.md, charts/newrelic-k8s-metrics-adapter/ci/test-values.yaml, charts/newrelic-k8s-metrics-adapter/templates/_helpers.tpl, charts/newrelic-k8s-metrics-adapter/templates/adapter-clusterrolebinding.yaml, charts/newrelic-k8s-metrics-adapter/templates/adapter-rolebinding.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/apiservice.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/README.md, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrole.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrolebinding.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/psp.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/role.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/rolebinding.yaml, charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/serviceaccount.yaml, charts/newrelic-k8s-metrics-adapter/templates/configmap.yaml, charts/newrelic-k8s-metrics-adapter/templates/deployment.yaml, charts/newrelic-k8s-metrics-adapter/templates/hpa-clusterrole.yaml, charts/newrelic-k8s-metrics-adapter/templates/hpa-clusterrolebinding.yaml, charts/newrelic-k8s-metrics-adapter/templates/secret.yaml, charts/newrelic-k8s-metrics-adapter/templates/service.yaml, charts/newrelic-k8s-metrics-adapter/templates/serviceaccount.yaml, charts/newrelic-k8s-metrics-adapter/values.yaml
This PR only has the Helm chart to focus other PRs on the changes that matter like the CI of adapting it to use the common library.
=> Copy the helm chart to this repo

.github/workflows/release-chart.yml
- Add the required newrelic helm repo to the pipeline
=> Add newrelic helm repo to release pipeline

README.md, Tiltfile, charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/README.md, charts/newrelic-k8s-metrics-adapter/README.md.gotmpl, charts/newrelic-k8s-metrics-adapter/values.yaml
- Modify the chart Readme autogenerating it with helm-docs
- Correct repo Readme
- Correct Tilt
=> Chart docs

.github/workflows/ci.yaml, charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/ci/test-values.yaml, charts/newrelic-k8s-metrics-adapter/templates/secret.yaml
Linked to https://github.com/newrelic/newrelic-coreint/issues/314
=> feat(cicd): test install and upgrade of charts

README.md
Fix the route to the chart in the ReadMe
=> Fix the route to the chart in the ReadMe

charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/README.md, charts/newrelic-k8s-metrics-adapter/values.yaml
Add proxy config value in the chart `README.md`.
Disclaimer: You'll see several changes because I indented the table properly in order to be easy to read and update it for us.
=> Add proxy documentation with helm-docs

charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/README.md, charts/newrelic-k8s-metrics-adapter/tests/apiservice_test.yaml
Relates to https://github.com/newrelic/helm-charts/issues/845.
Fix url to point to the proper branch.
=> Fix helm chart url

go.mod, go.sum
Fixes https://github.com/advisories/GHSA-cg3q-j54f-5p7p.
=> Bump github.com/prometheus/client_golang from 1.11.0 to 1.11.1

.github/renovate.json5
=> Update Renovate configs

.github/renovate.json5
=> Update RenovateBot settings

.github/workflows/ci.yaml, .github/workflows/release-integration.yml
=> Remove manual go cache since setup-go/v4 automatically caches

charts/newrelic-k8s-metrics-adapter/Chart.yaml
=> Bump chart

.github/workflows/ci.yaml
=> Update golangci-lint config to avoid cache contention

CHANGELOG.md, charts/newrelic-k8s-metrics-adapter/Chart.yaml
=> chore: Remove old maintainers

.github/workflows/security.yaml
Add permissions to security workflow otherwise it'll fail. 
=> Add permissions

.github/PULL_REQUEST_TEMPLATE.md
Please include a summary of the change in your pr and what it's fixing. 
=> ci: Simplify PR template

.github/workflows/security.yaml
Reduce redundant code and simplify code maintenance by making the security workflow reusable.
=> ci: Update 'Security Scan' workflow to be reusable

.github/renovate.json5, CHANGELOG.md
=> fix: Fix renovate config file

.github/renovate.json5
=> ci: Fix Renovate config file

.github/workflows/ci.yaml, CHANGELOG.md
=> chore: Remove 1.23 support

.github/workflows/ci.yaml, CHANGELOG.md
=> chore: Add k8s v1.28.0-rc.1 support 

.github/workflows/ci.yaml
Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)
=> fix: Disable semgrep action that has been deprecated

.github/workflows/ci.yaml, CHANGELOG.md
=> chore: Replace k8s v1.28.0-rc.1 with k8s 1.28.3 support

CHANGELOG.md, README.md, test-e2e.sh, test-integration.sh
Simplify locally running integration and E2E tests
=> feat: Automate local integration and E2E testing

go.mod, go.sum
=> chore: update module k8s.io/klog/v2 to v2.110.1

.github/workflows/ci.yaml, CHANGELOG.md, Makefile, README.md
=> ci: add codecov

charts/newrelic-k8s-metrics-adapter/Chart.yaml, charts/newrelic-k8s-metrics-adapter/README.md
=> chore: update maintainers

.github/workflows/ci.yaml
=> chore: update codecov config

.github/workflows/release-integration.yml
=> chore: Update secrets

.github/workflows/ci.yaml
=> Update codespell ignore list.

.github/workflows/ci.yaml, CHANGELOG.md
=> Add 1.29 and 1.30 support

.github/workflows/ci.yaml, CHANGELOG.md
=> feat: Add Kube 1.31 support and drop 1.26

charts/newrelic-k8s-metrics-adapter/README.md
Duplicates https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/389 with passing tests
=> update open source banner in chart readme

go.mod, go.sum
Dependabot deleted the other branch for some reason.
=> deps: update newrelic-client-go

.github/workflows/changelog.yml, .github/workflows/ci.yaml, .github/workflows/repolinter.yml, .github/workflows/trigger-release.yml
=> chore: Update GHA perms

.github/workflows/ci.yaml, CHANGELOG.md
=> feat: add k8s support v1.33 and remove support for v1.28
