newrelic/newrelic-k8s-metrics-adapter

- .github/workflows/ci.yaml
Yesterday’s Github outage did not run pipelines when #40 was merged to main. I am doing this quick and stupid PR to force a run of the pipeline to release the helm chart.
It is based on the review @roobre gave @paologallinaharbur [here](https://github.com/newrelic/nri-kubernetes/pull/377#discussion_r834463880) and fixed [here](https://github.com/newrelic/nri-kubernetes/pull/377/commits/78a9c38da16ed3f9151ada0173ce58ecd91d3b5f).
> Run release pipeline again

- charts/newrelic-k8s-metrics-adapter/Chart.lock
- charts/newrelic-k8s-metrics-adapter/Chart.yaml
- charts/newrelic-k8s-metrics-adapter/templates/_helpers.tpl
- charts/newrelic-k8s-metrics-adapter/templates/adapter-clusterrolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/adapter-rolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/apiservice.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrole.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/psp.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/role.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/rolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/serviceaccount.yaml
- charts/newrelic-k8s-metrics-adapter/templates/configmap.yaml
- charts/newrelic-k8s-metrics-adapter/templates/deployment.yaml
- charts/newrelic-k8s-metrics-adapter/templates/hpa-clusterrole.yaml
- charts/newrelic-k8s-metrics-adapter/templates/hpa-clusterrolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/secret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/service.yaml
- charts/newrelic-k8s-metrics-adapter/templates/serviceaccount.yaml
- charts/newrelic-k8s-metrics-adapter/tests/job_patch_job_createsecret_test.yaml
- charts/newrelic-k8s-metrics-adapter/tests/job_patch_job_patchapiservice_test.yaml
- charts/newrelic-k8s-metrics-adapter/values.yaml
This chart used the override system we should get rid of.
This PR should upgrade the common library and fix the issue of charts overwriting each other its helpers.
> Upgrade common library to 1.x

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
I don't know when and how I finished updating the image `tag`/chart's `appVersion` but I did it.
This should fix this chart making it installable.
> fix appVersion

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
- charts/newrelic-k8s-metrics-adapter/templates/_helpers.tpl
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/clusterrolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/rolebinding.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/serviceaccount.yaml
- charts/newrelic-k8s-metrics-adapter/templates/serviceaccount.yaml
- charts/newrelic-k8s-metrics-adapter/tests/job_serviceaccount_test.yaml
- charts/newrelic-k8s-metrics-adapter/tests/rbac_test.yaml
There is an issue open by GTS saying that not all the charts honor the flag `.global.serviceAccount.create` and `.global.serviceAccount.name`: newrelic/helm-charts#875
There is not also the issue that they are not honored by the deployments but also by the jobs that create and patch webhook certificates.
>  [helm chart] Patch job should also honor the global service account flag

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
We had a clash of chart versions after pipelines passed:
- https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/75
- https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/76
So, I am bumping and releasing the chart.
> Bump the chart

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
- charts/newrelic-k8s-metrics-adapter/templates/deployment.yaml
We were using `labels` instead of `podLabels` in the pods so we were not leveraging the `common-library` properly.
Fixes newrelic/nri-kube-events#142
> [chart] Fix `podLabels`

- charts/newrelic-k8s-metrics-adapter/Chart.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml
Relates to https://github.com/newrelic/helm-charts/issues/932.
NodeSelectors are not being honoured in the jobs objects.
> NEWRELIC-3912 Add nodeSelector support for jobs 

- go.mod
- go.sum
Bump dependency to address https://github.com/advisories/GHSA-gwc9-m7rh-j2ww.
> Bump golang.org/x/crypto to v0.1.0

- .github/workflows/ci.yaml
The `set-output` command is deprecated and will be fully disabled this May:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This will clean up the warnings when running the Github workflow.
> Update deprecated GitHub set-output action

- .github/ct.yaml
- .github/workflows/release-chart.yml
This PR makes it easier to make changes to the helm chart without needing to also bump the version in the same PR.
- Check that future PRs that modify the chart (like https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/101) won't fail the `Helm lint` test that requires the chart version be bumped.
> Update helm chart release process

- .github/workflows/ci.yaml
- Add caching for go builds when running helm tests
- Remove dep between build step and integration test
since the latter builds it's own binary
> Speedup CI workflow

- .github/workflows/ci.yaml
Helm v3.10 uses k8s client go v0.25.2 which shouldn't
suffer from https://github.com/helm/helm/issues/11772
Once the issue is released in an upstream version of
client-go and then helm is upgraded to use it, we can
switch to that version of helm.
> Explicitly install a controlled version of helm and kubectl

- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-createSecret.yaml
- charts/newrelic-k8s-metrics-adapter/templates/apiservice/job-patch/job-patchAPIService.yaml
- charts/newrelic-k8s-metrics-adapter/tests/job_patch_job_createsecret_test.yaml
- charts/newrelic-k8s-metrics-adapter/tests/job_patch_job_patchapiservice_test.yaml
- charts/newrelic-k8s-metrics-adapter/values.yaml
- e2e/e2e_test.go
k8s.gcr.io image registry will be redirected to registry.k8s.io on Monday March 20th.
All images available in k8s.gcr.io are available at registry.k8s.io.
See https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
> Update Kubernetes image registry

- .github/workflows/release-integration.yml
GitHub Actions is deprecating `save-state` and `set-output` commands. They will be fully disabled on 31st May 2023. [Source](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
> Update Docker actions to cope with deprecated `save-state` and `set-output` commands

- .github/workflows/ci.yaml
- CHANGELOG.md
- charts/newrelic-k8s-metrics-adapter/README.md
Remove old maintainers from readme and fix CI workflow. 
The --container-runtime flag was deprecated in k8s 1.24, and removed in k8s 1.27
So the e2e test for 1.27.5 with minikube fails. Fixed by adding start `args: "--nodes=2 --container-runtime=${{ matrix.cri }}"` which is what we did in nri-kubenetes and nri-kube-events repo
NA
> chore: Fix CI workflow and remove old maintainers

- Makefile
Since we're using the release integration workflow from metadata-injection, it uses `make compile` command which doesn't exist in this repo's Makefile because it was called `make build`. 
This pr adds the `compile` command that executes the `build` command. 
> fix: Add compile command to makefile

- .github/workflows/release-integration.yml
Test release docker image workflow with calling a reusable workflow
> fix: Tmp remove reusable workflow from release docker image

- .github/workflows/release-integration.yml
- Dockerfile
Replace release docker image workflow with reusable workflow. 
> fix: Update jobs to use reusable workflow to release docker image

- .github/workflows/release-chart.yml
- .github/workflows/release-integration.yml
Automate workflow notifications to Slack. That way we have only one source of truth to check for failing workflows.
For workflows that run for PRs, there is no need for automatic Slack notifications since merging will be blocked in the corresponding PR and author will be notified.
> ci: Add Slack notifications to all workflows that do not involve PRs

- .github/workflows/ci.yaml
Updating minikube version so Helm chart linting works for Kubernetes v 1.27
> ci: Update minikube version

- CHANGELOG.md
- go.mod
- go.sum
Following dependabot recommendation fix to bump google.golang.org/grpc from 1.58.2 to 1.58.3
This prs replaces this one that was having issues access github secret in order to run integration tests: https://github.com/newrelic/newrelic-k8s-metrics-adapter/pull/236
> chore: Bump google.golang.org/grpc from 1.58.2 to 1.58.3

- CHANGELOG.md
- e2e/e2e_test.go
- hack/kind-with-registry.sh
HPA has been promoted to [stable](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
> feat: E2E testing: use `autoscaling/v2` instead of `autoscaling/v2beta2`

- .github/workflows/ci.yaml
- CHANGELOG.md
Upgrade supported k8s version to v1.32.0 and drop v1.27.0
> feat: Upgrade supported k8s version to v1.32.0 and drop v1.27.0

- CHANGELOG.md
The supposed release on 4/28 never actually happened because the version didn't increase properly -> https://github.com/newrelic/newrelic-k8s-metrics-adapter/commit/04bf202b82d1ec8099c3d2483b43c0e422a6ccc9
I think the release toolkit didn't recognize `dependency` properly. The options for non-dependabot changes are `enhancement`, `security`, `bugfix`, and `breaking`.
> fix: potentially bad formatting prevented version increase and made everything weird
